/**
 * 馬プロファイルデータ (30頭)
 *
 * 中央芝/中央ダート/地方ダートの各カテゴリに分散。
 * 種牡馬は意図的に重複させて統計分析で有意なサンプルが出るようにしている。
 */

import type { HorseProfile } from './seed-helpers';

// ==================== 中央・芝 ====================

const turfHorses: HorseProfile[] = [
  // --- 中距離 (1800-2200) ---
  {
    id: 'h001', name: 'サンダーボルト', age: 4, sex: '牡', color: '鹿毛',
    birthDate: '2022-03-15', fatherName: 'ディープインパクト', motherName: 'スターライト',
    trainerName: '藤沢和雄', ownerName: 'サンデーレーシング',
    ability: 78, preferredTrack: '芝', bestDistance: 2000, distanceFlex: 200,
    style: '先行', heavyBonus: -5, consistency: 0.12, finishKick: 34.0,
    preferredCourses: ['東京', '阪神'], usualJockey: 'ルメール', baseWeight: 488,
    totalRaces: 12, wins: 5, seconds: 3, thirds: 1, totalEarnings: 28500,
    strengths: ['芝の中距離で安定した成績', '先行力が高く好位から抜け出せる', '右回りコースが得意'],
    weaknesses: ['重馬場では成績が落ちる', '多頭数のレースでは揉まれ弱い'],
    bestMonths: [3, 4, 10, 11],
  },
  {
    id: 'h002', name: 'ミラクルクイーン', age: 4, sex: '牝', color: '栗毛',
    birthDate: '2022-04-20', fatherName: 'キングカメハメハ', motherName: 'ビューティフルドリーム',
    trainerName: '国枝栄', ownerName: 'キャロットファーム',
    ability: 76, preferredTrack: '芝', bestDistance: 1800, distanceFlex: 300,
    style: '差し', heavyBonus: -3, consistency: 0.15, finishKick: 33.5,
    preferredCourses: ['東京', '京都'], usualJockey: '横山武史', baseWeight: 462,
    totalRaces: 10, wins: 4, seconds: 2, thirds: 2, totalEarnings: 22000,
    strengths: ['瞬発力に優れ末脚が強烈', '東京コースの成績が抜群', '牝馬ながら牡馬相手にも善戦'],
    weaknesses: ['スタートが安定しない', '短距離は適性外'],
    bestMonths: [5, 6, 10],
  },
  {
    id: 'h003', name: 'ゴールドラッシュ', age: 5, sex: '牡', color: '黒鹿毛',
    birthDate: '2021-02-10', fatherName: 'ゴールドシップ', motherName: 'ダイヤモンドレディ',
    trainerName: '矢作芳人', ownerName: 'シルクレーシング',
    ability: 80, preferredTrack: '芝', bestDistance: 2200, distanceFlex: 400,
    style: '先行', heavyBonus: 15, consistency: 0.18, finishKick: 34.8,
    preferredCourses: ['中山', '阪神'], usualJockey: '川田将雅', baseWeight: 502,
    totalRaces: 18, wins: 6, seconds: 4, thirds: 3, totalEarnings: 45000,
    strengths: ['道悪の鬼、重馬場で本領発揮', '長距離戦に強い', 'G1実績あり'],
    weaknesses: ['良馬場のスプリントは苦手', '間隔が空くと調整が難しい'],
    bestMonths: [6, 12],
  },
  {
    id: 'h005', name: 'フォレストウィンド', age: 5, sex: '牝', color: '青鹿毛',
    birthDate: '2021-05-22', fatherName: 'ハーツクライ', motherName: 'グリーンブリーズ',
    trainerName: '友道康夫', ownerName: '社台レースホース',
    ability: 74, preferredTrack: '芝', bestDistance: 1800, distanceFlex: 200,
    style: '先行', heavyBonus: 5, consistency: 0.10, finishKick: 34.5,
    preferredCourses: ['中山', '福島'], usualJockey: '松山弘平', baseWeight: 458,
    totalRaces: 15, wins: 4, seconds: 3, thirds: 2, totalEarnings: 31000,
    strengths: ['中山コースの鬼', '先行して粘り込む走りが持ち味', '冬場に成績が上がる'],
    weaknesses: ['左回りはやや苦手', '夏場は成績が落ちる'],
    bestMonths: [1, 2, 12],
  },
  {
    id: 'h006', name: 'ダークナイト', age: 4, sex: '牡', color: '青毛',
    birthDate: '2022-02-28', fatherName: 'エピファネイア', motherName: 'ナイトクイーン',
    trainerName: '池江泰寿', ownerName: 'サンデーレーシング',
    ability: 75, preferredTrack: '芝', bestDistance: 2000, distanceFlex: 300,
    style: '差し', heavyBonus: 0, consistency: 0.16, finishKick: 33.8,
    preferredCourses: ['東京', '阪神'], usualJockey: '戸崎圭太', baseWeight: 480,
    totalRaces: 11, wins: 3, seconds: 2, thirds: 3, totalEarnings: 19500,
    strengths: ['差し脚が鋭い', '大舞台で力を発揮するタイプ', '距離延長で成績向上'],
    weaknesses: ['前が塞がると脆い', '小回りコースが苦手'],
  },
  {
    id: 'h007', name: 'レインボーブリッジ', age: 3, sex: '牡', color: '栗毛',
    birthDate: '2023-04-05', fatherName: 'サトノダイヤモンド', motherName: 'レインボーローズ',
    trainerName: '木村哲也', ownerName: 'キャロットファーム',
    ability: 73, preferredTrack: '芝', bestDistance: 2400, distanceFlex: 400,
    style: '追込', heavyBonus: 2, consistency: 0.20, finishKick: 33.2,
    preferredCourses: ['東京', '中京'], usualJockey: '坂井瑠星', baseWeight: 472,
    totalRaces: 5, wins: 2, seconds: 2, thirds: 0, totalEarnings: 8500,
    strengths: ['末脚の破壊力が魅力', '広いコースで本領発揮', '成長途上で伸びしろ大'],
    weaknesses: ['経験不足', '揉まれ弱い面がある'],
  },
  {
    id: 'h008', name: 'サクラチヨノオー', age: 6, sex: '牡', color: '鹿毛',
    birthDate: '2020-03-14', fatherName: 'オルフェーヴル', motherName: 'サクラプリンセス',
    trainerName: '手塚貴久', ownerName: '社台レースホース',
    ability: 77, preferredTrack: '芝', bestDistance: 2500, distanceFlex: 500,
    style: '先行', heavyBonus: 8, consistency: 0.09, finishKick: 35.0,
    preferredCourses: ['中山', '阪神', '京都'], usualJockey: '武豊', baseWeight: 496,
    totalRaces: 25, wins: 7, seconds: 5, thirds: 4, totalEarnings: 55000,
    strengths: ['重賞実績豊富なベテラン', '安定感抜群で大崩れしない', 'どの条件でもまとめる能力'],
    weaknesses: ['年齢的な衰え', '瞬発力勝負では分が悪い'],
    bestMonths: [3, 4, 11, 12],
  },
  {
    id: 'h009', name: 'ブレイブハート', age: 4, sex: '牡', color: '黒鹿毛',
    birthDate: '2022-05-10', fatherName: 'モーリス', motherName: 'カレッジガール',
    trainerName: '中内田充正', ownerName: 'ノーザンファーム',
    ability: 79, preferredTrack: '芝', bestDistance: 1800, distanceFlex: 300,
    style: '差し', heavyBonus: 3, consistency: 0.13, finishKick: 33.6,
    preferredCourses: ['阪神', '京都'], usualJockey: '川田将雅', baseWeight: 486,
    totalRaces: 9, wins: 4, seconds: 1, thirds: 2, totalEarnings: 25000,
    strengths: ['芝・ダート兼用の万能型', 'どんなペースにも対応可能', '阪神コースが大得意'],
    weaknesses: ['福島・小倉など小回りはやや苦手', '休み明けは割引'],
    bestMonths: [4, 5, 10, 11],
  },
  {
    id: 'h013', name: 'ノーブルファンタジー', age: 4, sex: '牡', color: '鹿毛',
    birthDate: '2022-01-20', fatherName: 'ディープインパクト', motherName: 'ノーブルローズ',
    trainerName: '堀宣行', ownerName: 'ノーザンファーム',
    ability: 76, preferredTrack: '芝', bestDistance: 2000, distanceFlex: 200,
    style: '差し', heavyBonus: -2, consistency: 0.14, finishKick: 33.4,
    preferredCourses: ['東京', '中京'], usualJockey: 'ルメール', baseWeight: 478,
    totalRaces: 10, wins: 3, seconds: 3, thirds: 1, totalEarnings: 20000,
    strengths: ['末脚のキレは一級品', '直線の長いコースで真価を発揮', 'ディープ産駒らしい瞬発力'],
    weaknesses: ['小回りは苦手', '良馬場でないと力を出し切れない'],
    bestMonths: [5, 6, 10],
  },
  {
    id: 'h014', name: 'ロイヤルパレス', age: 5, sex: '牡', color: '栗毛',
    birthDate: '2021-03-08', fatherName: 'エピファネイア', motherName: 'プリンセスティアラ',
    trainerName: '友道康夫', ownerName: 'シルクレーシング',
    ability: 77, preferredTrack: '芝', bestDistance: 2000, distanceFlex: 300,
    style: '先行', heavyBonus: 4, consistency: 0.11, finishKick: 34.2,
    preferredCourses: ['阪神', '京都'], usualJockey: '松山弘平', baseWeight: 492,
    totalRaces: 16, wins: 5, seconds: 4, thirds: 2, totalEarnings: 38000,
    strengths: ['好位から確実に差してくる', '重賞で安定した成績', 'エピファネイア産駒の典型的な先行力'],
    weaknesses: ['距離が2400mを超えるとやや甘い', '東京コースは合わない'],
    bestMonths: [3, 4, 9, 10],
  },
  {
    id: 'h019', name: 'タイムフライヤー', age: 4, sex: '牡', color: '青毛',
    birthDate: '2022-04-12', fatherName: 'ハーツクライ', motherName: 'タイムレスビューティー',
    trainerName: '藤原英昭', ownerName: 'サンデーレーシング',
    ability: 74, preferredTrack: '芝', bestDistance: 2200, distanceFlex: 400,
    style: '追込', heavyBonus: 0, consistency: 0.22, finishKick: 33.0,
    preferredCourses: ['東京', '中京'], usualJockey: '岩田望来', baseWeight: 476,
    totalRaces: 8, wins: 2, seconds: 2, thirds: 1, totalEarnings: 14000,
    strengths: ['上がり最速を連発する末脚', '広いコースで大爆発', 'ハーツクライ産駒らしいスケール'],
    weaknesses: ['展開に左右される', '小回りコースでは力を出せない', 'ムラが大きい'],
    bestMonths: [5, 11],
  },
  {
    id: 'h020', name: 'エターナルグロウ', age: 4, sex: '牡', color: '黒鹿毛',
    birthDate: '2022-02-05', fatherName: 'キタサンブラック', motherName: 'エターナルローズ',
    trainerName: '矢作芳人', ownerName: 'キャロットファーム',
    ability: 75, preferredTrack: '芝', bestDistance: 2400, distanceFlex: 400,
    style: '先行', heavyBonus: 6, consistency: 0.15, finishKick: 34.6,
    preferredCourses: ['京都', '阪神'], usualJockey: '武豊', baseWeight: 498,
    totalRaces: 9, wins: 3, seconds: 1, thirds: 2, totalEarnings: 18000,
    strengths: ['スタミナ豊富で長距離に適性', 'キタサンブラック産駒らしい先行力', '道悪もこなせる'],
    weaknesses: ['スピード勝負になると厳しい', 'マイル以下は距離不足'],
  },
  {
    id: 'h023', name: 'グランアルシオン', age: 5, sex: '牡', color: '栃栗毛',
    birthDate: '2021-04-18', fatherName: 'オルフェーヴル', motherName: 'グランフルール',
    trainerName: '池江泰寿', ownerName: 'ノーザンファーム',
    ability: 76, preferredTrack: '芝', bestDistance: 2000, distanceFlex: 300,
    style: '差し', heavyBonus: 10, consistency: 0.17, finishKick: 34.0,
    preferredCourses: ['阪神', '中山'], usualJockey: '戸崎圭太', baseWeight: 490,
    totalRaces: 14, wins: 4, seconds: 3, thirds: 2, totalEarnings: 30000,
    strengths: ['道悪になると能力が上がる', 'G2レベルで安定した成績', 'オルフェーヴル産駒の闘争心'],
    weaknesses: ['良馬場の瞬発力勝負だと甘い', '展開に左右される面あり'],
    bestMonths: [6, 7, 11, 12],
  },

  // --- マイル (1400-1600) ---
  {
    id: 'h015', name: 'シャイニングスター', age: 3, sex: '牝', color: '栗毛',
    birthDate: '2023-03-10', fatherName: 'ロードカナロア', motherName: 'シャイニングムーン',
    trainerName: '国枝栄', ownerName: 'ノーザンファーム',
    ability: 72, preferredTrack: '芝', bestDistance: 1400, distanceFlex: 200,
    style: '逃げ', heavyBonus: -4, consistency: 0.18, finishKick: 34.8,
    preferredCourses: ['東京', '中山'], usualJockey: '横山武史', baseWeight: 448,
    totalRaces: 5, wins: 2, seconds: 1, thirds: 1, totalEarnings: 7000,
    strengths: ['テンのスピードが速い', 'ゲートセンス抜群', '牝馬限定戦ではクラス上位'],
    weaknesses: ['キャリアが浅い', '揉まれると脆い'],
  },
  {
    id: 'h016', name: 'クリスタルウィング', age: 4, sex: '牝', color: '芦毛',
    birthDate: '2022-05-15', fatherName: 'モーリス', motherName: 'クリスタルレイン',
    trainerName: '中内田充正', ownerName: 'シルクレーシング',
    ability: 74, preferredTrack: '芝', bestDistance: 1600, distanceFlex: 200,
    style: '先行', heavyBonus: 2, consistency: 0.12, finishKick: 34.2,
    preferredCourses: ['阪神', '京都'], usualJockey: '川田将雅', baseWeight: 454,
    totalRaces: 10, wins: 3, seconds: 2, thirds: 2, totalEarnings: 18000,
    strengths: ['安定した先行力', 'モーリス産駒らしいパワー', '阪神マイルがベスト条件'],
    weaknesses: ['2000m以上は距離が長い', '東京の直線が長いコースは不向き'],
    bestMonths: [3, 4, 9, 10],
  },
  {
    id: 'h024', name: 'ドリームキャッチャー', age: 3, sex: '牡', color: '鹿毛',
    birthDate: '2023-02-22', fatherName: 'ディープインパクト', motherName: 'ドリームメイカー',
    trainerName: '木村哲也', ownerName: 'サンデーレーシング',
    ability: 71, preferredTrack: '芝', bestDistance: 1600, distanceFlex: 200,
    style: '差し', heavyBonus: -3, consistency: 0.19, finishKick: 33.8,
    preferredCourses: ['東京', '新潟'], usualJockey: '坂井瑠星', baseWeight: 470,
    totalRaces: 4, wins: 2, seconds: 1, thirds: 0, totalEarnings: 6000,
    strengths: ['ディープ産駒の王道の末脚', '直線が長いコースで爆発力', '素質は高い'],
    weaknesses: ['キャリア不足', '馬体重の変動が大きい', '重馬場は未経験'],
  },

  // --- スプリント (1000-1200) ---
  {
    id: 'h017', name: 'フラッシュアロー', age: 5, sex: '牡', color: '鹿毛',
    birthDate: '2021-01-25', fatherName: 'ロードカナロア', motherName: 'フラッシュレディ',
    trainerName: '藤沢和雄', ownerName: 'キャロットファーム',
    ability: 75, preferredTrack: '芝', bestDistance: 1200, distanceFlex: 200,
    style: '逃げ', heavyBonus: -2, consistency: 0.14, finishKick: 35.5,
    preferredCourses: ['中京', '小倉', '新潟'], usualJockey: '岩田望来', baseWeight: 482,
    totalRaces: 18, wins: 5, seconds: 3, thirds: 3, totalEarnings: 25000,
    strengths: ['ハナを切れるスピード', 'ロードカナロア産駒らしい短距離適性', '直線でもう一伸び'],
    weaknesses: ['1400m以上は距離が長い', '同型の逃げ馬が多いと厳しい'],
    bestMonths: [7, 8, 9],
  },
  {
    id: 'h025', name: 'シルバーウィンド', age: 4, sex: '牡', color: '芦毛',
    birthDate: '2022-03-30', fatherName: 'キングカメハメハ', motherName: 'シルバーレイン',
    trainerName: '手塚貴久', ownerName: '社台レースホース',
    ability: 72, preferredTrack: '芝', bestDistance: 1200, distanceFlex: 200,
    style: '先行', heavyBonus: 1, consistency: 0.13, finishKick: 35.0,
    preferredCourses: ['小倉', '新潟', '中京'], usualJockey: '松山弘平', baseWeight: 476,
    totalRaces: 12, wins: 3, seconds: 2, thirds: 3, totalEarnings: 15000,
    strengths: ['好位から抜け出すスプリント力', '夏場のローカル開催で好成績', '安定した先行力'],
    weaknesses: ['重賞レベルでは力不足', 'G1クラスとの対戦では厳しい'],
    bestMonths: [7, 8, 9],
  },
];

// ==================== 中央・ダート ====================

const dirtHorses: HorseProfile[] = [
  {
    id: 'h004', name: 'スピードスター', age: 3, sex: '牡', color: '芦毛',
    birthDate: '2023-01-08', fatherName: 'ロードカナロア', motherName: 'フラッシュダンス',
    trainerName: '堀宣行', ownerName: 'ノーザンファーム',
    ability: 77, preferredTrack: 'ダート', bestDistance: 1400, distanceFlex: 200,
    style: '逃げ', heavyBonus: 3, consistency: 0.15, finishKick: 36.0,
    preferredCourses: ['東京', '中山'], usualJockey: 'ルメール', baseWeight: 490,
    totalRaces: 6, wins: 3, seconds: 1, thirds: 1, totalEarnings: 12000,
    strengths: ['圧倒的なスピードの持ち主', 'ダートの短距離で無敵', 'ゲートの出が非常に良い'],
    weaknesses: ['芝は未経験', '距離延長に課題'],
  },
  {
    id: 'h010', name: 'フェニックス', age: 3, sex: '牝', color: '栃栗毛',
    birthDate: '2023-02-18', fatherName: 'キタサンブラック', motherName: 'フェアリーテイル',
    trainerName: '藤原英昭', ownerName: 'シルクレーシング',
    ability: 72, preferredTrack: 'ダート', bestDistance: 1800, distanceFlex: 200,
    style: '差し', heavyBonus: 5, consistency: 0.16, finishKick: 36.5,
    preferredCourses: ['京都', '阪神'], usualJockey: '坂井瑠星', baseWeight: 456,
    totalRaces: 4, wins: 2, seconds: 1, thirds: 1, totalEarnings: 7000,
    strengths: ['ダートでパワフルな末脚', '道悪をこなせる', '牝馬限定戦ではクラス上位'],
    weaknesses: ['キャリアが浅い', '馬体重の変動が大きい'],
  },
  {
    id: 'h018', name: 'ストームブレイカー', age: 5, sex: '牡', color: '黒鹿毛',
    birthDate: '2021-02-20', fatherName: 'キングカメハメハ', motherName: 'ストームクイーン',
    trainerName: '矢作芳人', ownerName: 'サンデーレーシング',
    ability: 78, preferredTrack: 'ダート', bestDistance: 1800, distanceFlex: 300,
    style: '先行', heavyBonus: 8, consistency: 0.11, finishKick: 36.2,
    preferredCourses: ['東京', '中京'], usualJockey: '戸崎圭太', baseWeight: 504,
    totalRaces: 16, wins: 6, seconds: 3, thirds: 2, totalEarnings: 42000,
    strengths: ['ダートの王者候補', '道悪で成績が上がる', '安定した先行力と持続力'],
    weaknesses: ['芝替わりは未知数', 'スローペースからの瞬発力勝負は苦手'],
    bestMonths: [1, 2, 11, 12],
  },
  {
    id: 'h021', name: 'アイアンハート', age: 4, sex: 'セ', color: '鹿毛',
    birthDate: '2022-03-05', fatherName: 'ゴールドシップ', motherName: 'アイアンレディ',
    trainerName: '池江泰寿', ownerName: 'キャロットファーム',
    ability: 73, preferredTrack: 'ダート', bestDistance: 1600, distanceFlex: 200,
    style: '差し', heavyBonus: 12, consistency: 0.14, finishKick: 36.8,
    preferredCourses: ['東京', '阪神'], usualJockey: '横山武史', baseWeight: 494,
    totalRaces: 11, wins: 3, seconds: 2, thirds: 2, totalEarnings: 16000,
    strengths: ['セン馬になり安定感が増した', '不良馬場でパフォーマンスが上がる', 'ゴールドシップ譲りの道悪適性'],
    weaknesses: ['良馬場ではやや平凡', '先行馬に展開を支配されると厳しい'],
    bestMonths: [6, 7],
  },
  {
    id: 'h026', name: 'ダークフレイム', age: 3, sex: '牡', color: '青毛',
    birthDate: '2023-04-10', fatherName: 'エピファネイア', motherName: 'ダークビューティー',
    trainerName: '中内田充正', ownerName: 'ノーザンファーム',
    ability: 70, preferredTrack: 'ダート', bestDistance: 1800, distanceFlex: 200,
    style: '追込', heavyBonus: 2, consistency: 0.22, finishKick: 36.0,
    preferredCourses: ['東京', '中京'], usualJockey: '岩田望来', baseWeight: 478,
    totalRaces: 4, wins: 1, seconds: 1, thirds: 1, totalEarnings: 4500,
    strengths: ['ダートの追込馬として展開次第で爆発', 'エピファネイア産駒の底力', '広いコースで力を発揮'],
    weaknesses: ['展開に左右される', 'キャリアが浅い', '小回りは苦手'],
  },
  {
    id: 'h027', name: 'ライトニングストーム', age: 5, sex: '牡', color: '栗毛',
    birthDate: '2021-03-15', fatherName: 'サウスヴィグラス', motherName: 'ライトニングガール',
    trainerName: '手塚貴久', ownerName: '社台レースホース',
    ability: 74, preferredTrack: 'ダート', bestDistance: 1200, distanceFlex: 200,
    style: '逃げ', heavyBonus: 5, consistency: 0.13, finishKick: 37.0,
    preferredCourses: ['東京', '中山'], usualJockey: 'ルメール', baseWeight: 486,
    totalRaces: 14, wins: 4, seconds: 3, thirds: 2, totalEarnings: 20000,
    strengths: ['ダート短距離のスペシャリスト', 'サウスヴィグラス譲りのスピード', '逃げ切り勝ちが多い'],
    weaknesses: ['距離延長は厳しい', '同型が多いと消耗する'],
    bestMonths: [1, 2, 3],
  },
];

// ==================== 地方競馬 ====================

const localHorses: HorseProfile[] = [
  {
    id: 'h011', name: 'オオイノチカラ', age: 5, sex: '牡', color: '鹿毛',
    birthDate: '2021-04-01', fatherName: 'サウスヴィグラス', motherName: 'オオイノハナ',
    trainerName: '荒山勝徳', ownerName: '大井太郎',
    ability: 72, preferredTrack: 'ダート', bestDistance: 1600, distanceFlex: 200,
    style: '先行', heavyBonus: 5, consistency: 0.12, finishKick: 37.0,
    preferredCourses: ['大井', '川崎'], usualJockey: '御神本訓史', baseWeight: 486,
    totalRaces: 22, wins: 8, seconds: 5, thirds: 3, totalEarnings: 18000,
    strengths: ['大井ダート1600mが庭', '先行押切りの競馬が持ち味', '南関東重賞で実績あり'],
    weaknesses: ['中央馬相手では力不足', '1800m以上は距離が長い'],
    bestMonths: [1, 2, 10, 11],
  },
  {
    id: 'h012', name: 'カワサキスプリント', age: 4, sex: '牝', color: '栗毛',
    birthDate: '2022-03-25', fatherName: 'ホッコータルマエ', motherName: 'カワサキレディ',
    trainerName: '内田勝義', ownerName: '川崎次郎',
    ability: 70, preferredTrack: 'ダート', bestDistance: 1000, distanceFlex: 200,
    style: '逃げ', heavyBonus: 3, consistency: 0.14, finishKick: 37.5,
    preferredCourses: ['川崎', '浦和'], usualJockey: '森泰斗', baseWeight: 452,
    totalRaces: 16, wins: 6, seconds: 3, thirds: 2, totalEarnings: 14000,
    strengths: ['短距離のスペシャリスト', 'ゲートセンス抜群', '川崎900mの女王'],
    weaknesses: ['1400m以上は距離が長い', '中央遠征は未経験'],
  },
  {
    id: 'h022', name: 'フナバシキング', age: 6, sex: '牡', color: '鹿毛',
    birthDate: '2020-05-10', fatherName: 'サウスヴィグラス', motherName: 'フナバシクイーン',
    trainerName: '川島正行', ownerName: '船橋三郎',
    ability: 71, preferredTrack: 'ダート', bestDistance: 1400, distanceFlex: 200,
    style: '先行', heavyBonus: 4, consistency: 0.11, finishKick: 37.2,
    preferredCourses: ['船橋', '大井'], usualJockey: '笹川翼', baseWeight: 492,
    totalRaces: 28, wins: 9, seconds: 6, thirds: 4, totalEarnings: 22000,
    strengths: ['南関東の古豪', '船橋コースは庭同然', 'サウスヴィグラス産駒の先行力'],
    weaknesses: ['年齢的に衰えの兆し', 'スピード負けする場面が増えた'],
    bestMonths: [1, 2, 3, 10, 11, 12],
  },
  {
    id: 'h028', name: 'ウラワノホシ', age: 4, sex: '牡', color: '黒鹿毛',
    birthDate: '2022-04-08', fatherName: 'ホッコータルマエ', motherName: 'ウラワレディ',
    trainerName: '小久保智', ownerName: '浦和四郎',
    ability: 68, preferredTrack: 'ダート', bestDistance: 1400, distanceFlex: 200,
    style: '差し', heavyBonus: 6, consistency: 0.16, finishKick: 37.5,
    preferredCourses: ['浦和', '大井'], usualJockey: '矢野貴之', baseWeight: 480,
    totalRaces: 12, wins: 3, seconds: 2, thirds: 3, totalEarnings: 8000,
    strengths: ['浦和コースに強い', 'ホッコータルマエ産駒のパワー', '道悪で浮上するタイプ'],
    weaknesses: ['先行馬に楽逃げされると厳しい', '中央のスピードには対応できない'],
  },
  {
    id: 'h029', name: 'オオイノカゼ', age: 5, sex: '牡', color: '青鹿毛',
    birthDate: '2021-03-20', fatherName: 'ゴールドシップ', motherName: 'オオイノツバサ',
    trainerName: '荒山勝徳', ownerName: '大井太郎',
    ability: 70, preferredTrack: 'ダート', bestDistance: 2000, distanceFlex: 300,
    style: '追込', heavyBonus: 10, consistency: 0.20, finishKick: 36.8,
    preferredCourses: ['大井', '川崎'], usualJockey: '御神本訓史', baseWeight: 496,
    totalRaces: 18, wins: 4, seconds: 3, thirds: 4, totalEarnings: 15000,
    strengths: ['大井の長距離戦で爆発力', 'ゴールドシップ産駒らしい道悪適性', '展開がハマれば一発ある'],
    weaknesses: ['展開に左右される', '安定感に欠ける', '短距離は合わない'],
    bestMonths: [6, 7, 12],
  },
  {
    id: 'h030', name: 'ナイトフリート', age: 4, sex: '牡', color: '栗毛',
    birthDate: '2022-02-14', fatherName: 'キングカメハメハ', motherName: 'ナイトブリーズ',
    trainerName: '内田勝義', ownerName: '川崎次郎',
    ability: 69, preferredTrack: 'ダート', bestDistance: 1600, distanceFlex: 200,
    style: '先行', heavyBonus: 3, consistency: 0.15, finishKick: 37.0,
    preferredCourses: ['大井', '川崎'], usualJockey: '森泰斗', baseWeight: 484,
    totalRaces: 10, wins: 3, seconds: 2, thirds: 1, totalEarnings: 10000,
    strengths: ['南関東のマイル戦で安定', '先行力が武器', 'キングカメハメハ産駒の万能性'],
    weaknesses: ['重賞レベルでは力不足', '長距離は苦手'],
  },
];

// ==================== エクスポート ====================

export const ALL_HORSES: HorseProfile[] = [
  ...turfHorses,
  ...dirtHorses,
  ...localHorses,
];
